name: "Bambu Lab P1 - Spaghetti Detection Server"
description: "Obico ML server for detection spaghetti"
version: "1.0.0"
slug: "ha_bambu_lab_p1_spaghetti_detection_addon"
init: false
arch:
  - amd64
startup: services
ports:
  3333/tcp: 3333
options:
  obico_api_secret: "obico_api_secret"
schema:
  obico_api_secret: str